/line_follow:
  navigation:
    ros__parameters:
      navigation_type: 'simple'
      use_intra_process_comms: true
      qos_overrides:
        /down_camera/camera_node/image_raw:
          subscription:
            reliability: best_effort
            history: keep_last
            depth: 1
