name: Mirror to Target Repo

on:
  push:
    branches: [ "**" ]
  delete:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git remote add mirror https://${{ secrets.MIRROR_PAT }}@github.com/SGCS-SE/2026-at3-software-project-will-da-pro.git
          
          git push --mirror mirror
